from pathlib import Path


def get_project_root() -> Path:
    return Path(__file__).parent.parent


DATA_DIRECTORY = get_project_root() / 'data'
ALL_MODELS_FILE = DATA_DIRECTORY / 'all_models.csv'
TOP_MODELS_FILE = DATA_DIRECTORY / 'top_1000_models.csv'

README_FILE_DIRECTORY = DATA_DIRECTORY / 'readmes'
RAW_MODEL_CARD_DIRECTORY = README_FILE_DIRECTORY / 'raw'
PREPROCESSED_MODEL_CARD_DIRECTORY = README_FILE_DIRECTORY / 'preprocessed'
TOP_ONE_MODEL_PER_ORGANIZATION_FILE = DATA_DIRECTORY / 'top_one_model_per_organization.csv'
EXCLUDING_REPOS_FILE = DATA_DIRECTORY / 'excluding_repos.csv'
SELECTED_REPOS_FILE = DATA_DIRECTORY / 'selected_repos.csv'

REORGANIZED_MODEL_CARD_DIRECTORY = README_FILE_DIRECTORY / 'reorganized'
MODEL_CARD_INFO_LIST_DIRECTORY = README_FILE_DIRECTORY / 'info_list'
MANUAL_COMPLETENESS_VERIFICATION_RESULT_DIRECTORY = REORGANIZED_MODEL_CARD_DIRECTORY / 'manual_completeness_verification'


